app:
  name: 'Cobot Inspection'
  version: '0.0.1'
  release_date: undefined
  author: 'SSBHPE'
debug: True
camera:
  src: 0
  resolution: '1080x720'
  fps: 10
  save_path: 'captures'
  config:
    brightness: 0
    contrast: 0
    saturation: 0
    sharpness: 0
cobot:
  ip: '10.8.66.212'
  tcp_port: 
  modbus_port: 502
ml_model:
  size: 100
database:
  name: 'cobot.db'
