app:
  name: 'Cobot Inspection'
  version: '0.0.2'
  release_date: undefined
  author: 'SSBHPE'
debug: True
controller:
  debug_model: True  
camera:
  src: 0
  resolution: '640x480'
  fps: 15
  folder: 'temp'
  results_folder: 'results'
  debug: False
  config:
    brightness: 0
    contrast: 0
    saturation: 0
    sharpness: 0
cobot:
  ip: '10.8.66.212'
  tcp_port: 
  modbus_port: 502
models:
  path: 'keras_models'  
  size: 224
  channels: 3
database:
  name: 'cobot.db'
log:
  name: 'cobot_app'
  path:
  
