app:
  name: "Cobot Inspection"
  version: "0.1.0"
  created_at: 2020-10-01
  last_updated: 2021-03-31
  author: "SSBHPE"
debug: False
controller:
  debug_model: False
  process_after_shot: True
  components: ['7500','8734','7817', '7506', '9382'] # Transfer to database
camera:
  src: 1
  resolution: "640x480"
  window_size: [900, 700]
  full_screen: False
  inverted: True
  roi: []
  fps: 15
  folder: "temp"
  results_folder: "results"
  debug: False
  brightness: 127
  contrast: 127
  saturation: 127
  sharpness: 127
cobot:
  ip: "10.8.66.212"
  tcp_port: 0
  modbus_port: 502
  update_time: 0.2
models:
  path: "keras_models"
  size: 224
  channels: 3
database:
  server: '10.8.66.119'
  user: 'lts'
  password: 'lts123'
  database: 'LTS'
  workplace_id: 999
log:
  name: "cobot_app"
  path: "logs"
